# src/main/resources/application-dev.yml

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

logging:
  level:
    com.seal.hackathon: DEBUG
    org.springframework.web: DEBUG