package com.t7.seal.domain;

public enum AiIntent {
    PROJECT_HELP,
    TECH_EXPLANATION,
    TRANSLATION,
    DEBUG_GUIDANCE,
    SUBMISSION_HELP,
    TEAM_HELP,
    GRADING_HELP,
    RESULT_HELP,
    REMINDER_HELP,
    ACCESS_HELP,
    BLOCK_ASSIGNMENT_CODE,
    BLOCK_FULL_SOLUTION,
    BLOCK_PLAGIARISM_BYPASS,
    BLOCK_PRIVATE_DATA,
    OUT_OF_SCOPE,
    GENERAL_HELP
}
