package com.t7.seal.domain;

public enum AuditActionType {
    SCORE_CREATE,
    SCORE_UPDATE,
    TEAM_DISQUALIFIED,
    RANKING_RECALCULATED,
    TEAM_ADVANCED,
    ACCOUNT_APPROVED,
    ACCOUNT_SUSPENDED,
    JUDGE_ASSIGNED,
    TEAM_REGISTERED,
    SUBMISSION_LATE,
    CRITERIA_WEIGHT_CHANGED,
    RESULT_PUBLISHED,
    ADVANCEMENT_CONFIRMED,
    EMAIL_VERIFIED,
    PASSWORD_RESET,
    ROUND_LOCKED,
    ROUND_OPEN,
    ROUND_CLOSED,
    LEADERSHIP_TRANSFERRED,
    MENTOR_FEEDBACK_CREATED,
    MENTOR_FEEDBACK_UPDATED
}
