package com.t7.seal.domain;

public enum NotificationType {
    TEAM_INVITATION_SENT,
    TEAM_INVITATION_ACCEPTED,
    TEAM_INVITATION_REJECTED,
    RESULT_PUBLISHED,
    ROUND_OPENED,
    ROUND_CLOSED,
    TEAM_ADVANCED,
    TEAM_ELIMINATED,
    ACCOUNT_APPROVED,
    ACCOUNT_SUSPENDED,
    SUBMISSION_REMINDER,
    JUDGING_REMINDER,
    CALIBRATION_REMINDER,
    EMAIL_VERIFY,
    PASSWORD_RESET,
    MENTOR_FEEDBACK,
    GENERAL
}
