package com.t7.seal.domain;

public enum SubmissionBlockedReason {
    NONE,
    NOT_TEAM_LEADER,
    TRACK_NOT_ASSIGNED,
    TEAM_REGISTRATION_NOT_APPROVED,
    TEAM_ELIMINATED,
    TEAM_STATUS_NOT_ELIGIBLE,
    SUBMISSION_RESUBMISSION_REQUIRED,
    MISSING_REQUIRED_TYPES,
    ROUND_NOT_OPEN,
    ROUND_SUBMISSION_LOCKED,
    ROUND_SUBMISSION_DEADLINE_EXCEEDED
}
